### ISSUE TITLE
Default keyboard shortcut (cmd-shift-i) isn't valid in Windows or Linux

### ISSUE THREAD

**Issue by OttoRobotto** [griiin/atom-auto-indent#10]
I modified the shortcut to `ctrl-shift-a` because it's easy to reach, currently not in use, and a could logically be assumed to stand for Auto-Indent

**Comment by griiin** [comment]
My package is just using the "Editor: Indent" (it's basically doing "cmd+a cmd+i"), I think it makes sense to left cmd+shit+i.
But I'm glad that you can custom the key binding as you wish.
