### ISSUE TITLE
One line if statements don't indent properly

### ISSUE THREAD

**Issue by robbyemmert** [griiin/atom-auto-indent#11]
Examples:
<code>
if (somevar == true)
   doSomething();
</code>

and

<code>
if (somevar == true) { doSomething(); }
</code>

Continue the indent, not realizing that the if statement has ended.  Even if you consider one line if statements bad practice, they are used in many 3rd party libraries and generators, and should be handled.

Otherwise, awesome plugin!

Thanks,

**Comment by griiin** [comment]
My package is just using the "Editor: Indent" (it's basically doing "cmd+a cmd+i").
If there's an issue with the indentation you should create an issue on atom's repo.
