### ISSUE TITLE
Wrong indentation on multiline comment and block var statements

### ISSUE THREAD

**Issue by SamVerschueren** [griiin/atom-auto-indent#16]
When formatting using this library I have the following issues.

## Multiline comment

```JavaScript
/**
 * Comment block
 */
```

Shift + Cmd + I results in

```JavaScript
/**
* Comment block
*/
```

## Block var statement

```JavaScript
var mongoose = require('mongoose'),
    validator = require('validator'),
    _ = require('lodash');
```

Shift + Cmd + I results in

```JavaScript
var mongoose = require('mongoose'),
validator = require('validator'),
_ = require('lodash');
```

**Comment by griiin** [comment]
My package is just using the "Editor: Indent" (it's basically doing "cmd+a cmd+i").
If there's an issue with the indentation you should create an issue on atom's repo.
