### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [griiin/atom-auto-indent#23]
This package will not be loaded after June 1st without changes. There are a couple deprecations on the latest version of this package:

1. Use ::getActivePaneItem() instead of the ::activePaneItem property
1. atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
1. Use TextEditor::getLastCursor() instead

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see what deprecations are being reported on this package.

See https://github.com/atom/atom/issues/6867 for more info.

**Comment by NicolasKAROLAK** [comment]
@griiin 1st is tomorrow, can we hope to ave an upgrade ?

**Comment by eddiemonge** [comment]
@griiin Need help maintaining this?

**Comment by JaKXz** [comment]
+1

**Comment by griiin** [comment]
Sorry guys. Please update your packages.
Thanks for caring & sharing.
