### ISSUE TITLE
html multiline p format?

### ISSUE THREAD

**Issue by rakkarage** [griiin/atom-auto-indent#9]
A

    <!doctype html>
    <html>
    <body>
        <div>
            <p>Test0
                Test1</p>
        </div>
    </body>
    </html>

B

    <!doctype html>
    <html>
    <body>
        <div>
            <p>Test0
                Test1</p>
            </div>
        </body>
        </html>

editor.auto-indent formats a to b?
b is incorrectly formatted
c & d are formatted correctly
visual studio formats a to d
bug i guess or is that format illegal?
thanks

C

    <!doctype html>
    <html>
    <body>
        <div>
            <p>Test0 Test1</p>
        </div>
    </body>
    </html>

D

    <!doctype html>
    <html>
    <body>
        <div>
            <p>
                Test0
                Test1
            </p>
        </div>
    </body>
    </html>

**Comment by griiin** [comment]
My package is just using the "Editor: Indent" (it's basically doing "cmd+a cmd+i").
If there's an issue with the indentation you should create an issue on atom's repo.
